### ISSUE TITLE
"Open Operation" Search Unusable

### ISSUE THREAD

**Issue by bitm0de** [riok/Kreya#194] opened 2024-02-02 17:24 UTC
**Describe the bug**
The "Open Operation" quick search results are terribly inaccurate. It seems to be looking at characters too far apart with its fuzzy search functionality. I have an operation named exactly "SetAlarm" and it doesn't find it anywhere in the search results. It will find everything else not even closely related to my keyword.

**To Reproduce**
1. Use search (with a decent number of importers (6 in my case) that have at least 50 operations each.

**Expected behavior**
Search results are accurate/relevant.

**Screenshots**
![image](https://github.com/riok/Kreya/assets/14263968/d8fb4f4e-3edd-4234-a93e-c5e6e83eb4d5)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Windows 11
 - Kreya Version: 1.13.0 (2024-01-29)

**Comment by CommonGuy** [comment] 2024-02-02 18:46
Yes, this needs fixing.

**Comment by CommonGuy** [comment] 2024-02-09 12:37
We just released Kreya 1.13.1-alpha.1, which should fix this issue.

If you want to test this, go to Kreya -> About -> change the release channel to Alpha -> Check for updates -> Relaunch

**Comment by CommonGuy** [comment] 2024-02-12 14:40
Kreya 1.13.1 has been released, which should make the search more accurate

**Comment by bitm0de** [comment] 2024-02-13 21:48
![image](https://github.com/riok/Kreya/assets/14263968/af1d3461-d5e4-476b-9bb1-cf4cf6562ed0)

**Comment by CommonGuy** [comment] 2024-02-14 06:17
I am unable to reproduce this on 1.13.1:

![grafik](https://github.com/riok/Kreya/assets/8035999/8940b410-7138-4543-86f2-b7c197ca165f)

**Comment by CommonGuy** [comment] 2024-02-14 06:29
Did you make sure that you are in the "Open operation" quick action (shortcut Primary+O)? It is very easy to accidentally hit the "quick action overview" (shortcut Primary+K) and trying to enter the operation name there, which of course does not show any operations.

**Comment by CommonGuy** [comment] 2024-02-14 12:15
I found the error: We use [fuse.js](https://www.fusejs.io/) for searching, as that allows for fuzzy search. However, it looks like it only matches the first 60 characters by default: https://www.fusejs.io/api/options.html#ignorelocation. Your operation path (probably something like `very/long/directory/names/SetAlarm`) exceeds that limit, so it doesn't show up in search.

As for the current behaviour, we want to allow users to find operations in directory, for example an operation name "Delete" in the directory "Books" can be found with "delete book", the spelling does not have to be accurate. In the previous release, the [threshold](https://www.fusejs.io/api/options.html#threshold) was set way too high, resulting in too many unrelated matches.

We are going to fix this, sorry for the inconvenience.

**Comment by CommonGuy** [comment] 2024-03-13 14:49
A fix for this has been implemented and was released with the newest beta release. It will be included in the next stable version.

**Comment by CommonGuy** [comment] 2024-04-18 07:38
Kreya 1.14 has been released

**Closed by CommonGuy** 2024-04-18 07:38 UTC
Labels: bug, status:waiting-for-release
