### ISSUE TITLE
Expect UTF-8 support when returning a response

### ISSUE THREAD

**Issue by GuoXingyou** [riok/Kreya#69] opened 2021-12-22 03:41 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by latonz** [comment] 2021-12-22 07:59
This looks like a duplicate of https://github.com/riok/Kreya/issues/62. You can try the workaround described in https://github.com/riok/Kreya/issues/62#issuecomment-967105012 until the bugfix is released.

Closing as duplicate, feel free to reopen if the workaround doesn't work for you.

**Closed by latonz** 2021-12-22 07:59 UTC
Labels: enhancement

**Comment by GuoXingyou** [comment] 2021-12-22 08:10
thanks
