### ISSUE TITLE
Protobuf file 'xxx' is referenced, but was not found.

### ISSUE THREAD

**Issue by arkanmgerges** [riok/Kreya#37] opened 2021-05-29 09:18 UTC
**Describe the bug**
I'm trying to use reflection but I'm getting this error. I thought maybe my code has a problem but I've tested it with grpcui and it worked.
I attached image from your app and the other from the grpcui to show you that it's working on [grpcui ](https://github.com/fullstorydev/grpcui)(reflection method)
I'm using Windows 10 Pro

**Screenshots**
## On grpcui

![image](https://user-images.githubusercontent.com/7836805/120064919-6dc1f100-c077-11eb-955f-21ff527326be.png)

![image](https://user-images.githubusercontent.com/7836805/120064896-41a67000-c077-11eb-9530-4c635a228d73.png)

## On Kreya

![image](https://user-images.githubusercontent.com/7836805/120064903-508d2280-c077-11eb-948e-a3a42c39d1dd.png)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Windows 10 Pro, version: 20H2, build: 19042.985
 - Kreya Version 1.4.0

**Comment by arkanmgerges** [comment] 2021-05-29 10:31
Also I tried the reflection on [Wombat ](https://github.com/rogchap/wombat)and it worked,

![image](https://user-images.githubusercontent.com/7836805/120067007-0b222280-c082-11eb-854e-6273301717f7.png)

**Comment by CommonGuy** [comment] 2021-05-31 14:59
Strange, as we haven't had any problems with the server reflection importer before. Would you mind sharing your protobuf files with us? Either publicly here or via email (you can find it in my GitHub profile)?

**Comment by arkanmgerges** [comment] 2021-06-01 08:14
Hi, I've sent you an email with the protobuf files. Thank you.

**Comment by margru** [comment] 2021-06-11 13:23
I have exactly the same issue...

**Comment by CommonGuy** [comment] 2021-06-15 14:58
@margru @arkanmgerges Are you both using Python on the server-side? The [docs](https://github.com/grpc/grpc/blob/master/doc/python/server_reflection.md) state that you need to "manually register the service descriptors with the reflection service implementation when creating a server". Could this be the root cause?

**Comment by arkanmgerges** [comment] 2021-06-15 15:06
Hi @CommonGuy , yes I'm using python, and I've already registered the service descriptors, I've attached just part of the code as image. And also Wombat is does not have this problem and it's using the reflection from my server.

![image](https://user-images.githubusercontent.com/7836805/122077317-4ce1f580-ce04-11eb-9d0e-46953f133c01.png)

Thank you,
Arkan

**Comment by margru** [comment] 2021-06-15 15:17
@CommonGuy I can confirm that I am also using Python and I am manually registering the service descriptors.

**Comment by CommonGuy** [comment] 2021-06-15 15:47
Thanks for the quick answers, I'll try to reproduce it locally

**Comment by arkanmgerges** [comment] 2021-06-15 16:43
@CommonGuy also I've sent you my protobuf files more than 10 days ago as you asked,

Thank you,
Arkan

**Comment by CommonGuy** [comment] 2021-06-23 11:29
The python gRPC implementation causes this problem. We fixed it in our development branch, it will be released with the next Kreya version.

**Comment by CommonGuy** [comment] 2021-07-08 12:11
Kreya v1.5 was just released, which includes a fix for this bug.

**Closed by CommonGuy** 2021-07-08 12:11 UTC
Labels: bug, status:waiting-for-release
