### ISSUE TITLE
Kreya doesn't support to do a request after a failure anymore

### ISSUE THREAD

**Issue by ppcamp** [riok/Kreya#138] opened 2023-03-14 13:07 UTC
**Describe the bug**
Unfortunately, after update to this new version, when I do some request and it fails, if I try again it shows up `Support for parallel operation invocation is not part of the Free plan. Please upgrade to a paid plan to use it`. Thus, everytime I need to close kreya and initialize it again to try out other method.

**To Reproduce**
1. Open kreya and open some method
2. Do some unsuportted update
3. It will fail, then, if you try again, you'll see this message

**Expected behavior**
It should allow to do the next request after a failure

**Screenshots**

**Environment (if possible, copy the information from the error dialog or the About menu):**
 ```
 {
  "kreyaVersion": "1.10.0",
  "releaseChannel": "stable",
  "osDescription": "Microsoft Windows 10.0.22621",
  "osVersion": "Microsoft Windows NT 10.0.22621.0",
  "osArch": "X64",
  "processArch": "X64",
  "runtimeIdentifier": "win10-x64",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.69"
}
```

**Additional context**

**Comment by renaudjester** [comment] 2023-03-20 09:32
Same here! If I make a mistake in the request message and press start then I have to close restart the kreya app entirely to be able to make another request

**Comment by CommonGuy** [comment] 2023-03-22 07:21
Duplicate of https://github.com/riok/Kreya/issues/137. We are working on a bugfix and will release it soon.

**Closed by CommonGuy** 2023-03-22 07:21 UTC
Labels: bug
