### ISSUE TITLE
Retry on invalid_grant authentication

### ISSUE THREAD

**Issue by DominicMCN** [riok/Kreya#224] opened 2024-04-29 15:21 UTC
**Describe the bug**

When a refresh_token is expired, or environment changed (different credentials needed); a request authentication would fail. We would need to manually go to auth tab and click reset and update.

I vaguely remember a few versions ago, manual reset was not needed.

**To Reproduce**
1. Authenticates with OAuth
2. Let the token / refresh_token expires ; or change to a different environment which needs reauth
3. Request would fail

**Expected behavior**

Kreya retries authentication from the beginning of the OAuth flow at least one

**Comment by CommonGuy** [comment] 2024-05-01 05:21
Which Kreya version are you using? I am unable to reproduce this with Kreya 1.14.0. Invoking an operation automatically fetches a valid token for me.

When you switch to the details tab in the authentication, does the token show as invalid/expired?

**Comment by DominicMCN** [comment] 2024-05-01 10:05
1.14.1-beta 1

It does show as invalid-grant yea. I'll capture a screenshot when it expires again

**Comment by DominicMCN** [comment] 2024-05-01 13:59
<img width="722" alt="Screenshot 2024-05-01 at 14 58 05" src="https://github.com/riok/Kreya/assets/2601167/c355e00a-58c3-483c-a64e-f39ae7d18d5e">
<img width="539" alt="Screenshot 2024-05-01 at 14 58 18" src="https://github.com/riok/Kreya/assets/2601167/95fdb52b-3a41-40f4-b0c6-d82b6737ec10">

**Comment by CommonGuy** [comment] 2024-05-02 07:48
Ah now I got it. The bug only happens when a refresh token is present, but invalid/expired. We'll fix this in the next release

**Comment by CommonGuy** [comment] 2024-05-17 13:50
This has been fixed in the latest beta version and will be released in the next stable version

**Closed** 2024-06-12 09:42 UTC
Labels: bug, status:waiting-for-release
