### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by jkoenig134** [riok/Kreya#8] opened 2021-01-26 08:56 UTC
**Describe the bug**
When installing the application via the msi file there is an error.

**To Reproduce**
1. Download kreya for windows from [download site](https://kreya.app/downloads)
2. execute the downloaded msi file

**Expected behavior**
Kreya will be installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/33655937/105822655-9e582800-5fbc-11eb-9b6a-e2f1257f91b8.png)

**Environment:**
 - OS: Windows 10 20H2

**Comment by CommonGuy** [comment] 2021-01-26 10:06
Is your OS 64bit or 32bit? When does the error appear? Immediately after launching the MSI or after clicking "Install"?

I suspect that the WebView2 couldn't be installed correctly. Errors should be logged in the Windows Event Viewer. Could you post the relevant errors?

**Comment by jkoenig134** [comment] 2021-01-26 10:14
64 bit.
Error: 
```
Product: Kreya -- Error 1721. There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: DownloadAndInvokeBootstrapper, location: C:\Program Files\Kreya\, command: powershell.exe -windowstyle hidden Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile "$env:TEMP\MicrosoftEdgeWebview2Setup.exe" ; & $env:TEMP\MicrosoftEdgeWebview2Setup.exe /install
```

**Comment by jkoenig134** [comment] 2021-01-26 10:17
Possible workaround: installing WebView manual from [here](https://go.microsoft.com/fwlink/p/?LinkId=2124703)

**Comment by CommonGuy** [comment] 2021-01-26 19:43
I'm sorry, but so far I couldn't reproduce this error. Do you perhaps see more information in the Windows Event Viewer log? Maybe an error message what exactly went wrong?

Our installer package installs the WebView2 as recommended and shown in samples by Microsoft. Installing the WebView2 manually should work as a workaround.

**Comment by jkoenig134** [comment] 2021-01-26 19:44
I am sorry, no more related errors.

**Comment by CommonGuy** [comment] 2021-02-06 17:28
Closing since we cannot reproduce this.

**Closed by CommonGuy** 2021-02-06 17:28 UTC
Labels: bug

**Comment by webleaf** [comment] 2022-01-17 05:16
Same error on Windows 7 x64 during installation.
Windows Event Viewer log:

`Product: Kreya -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action DownloadAndInvokeBootstrapper, location: C:\Program Files\Kreya\, command: powershell.exe -windowstyle hidden Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile "$env:TEMP\MicrosoftEdgeWebview2Setup.exe" ; & $env:TEMP\MicrosoftEdgeWebview2Setup.exe /install `

Manual WebView2 installation does not help.

**Comment by Ba-la-laika** [comment] 2023-02-02 10:12
I was getting the same error. Try to place the file MicrosoftEdgeWebview2Setup.exe to the directory for the user's temporary files. The path is defined in the TEMP environment variable.
