### ISSUE TITLE
The latest version doesnt work on Linux

### ISSUE THREAD

**Issue by Serkan80** [riok/Kreya#40] opened 2021-07-20 09:42 UTC
**Describe the bug**
I've installed Kreya on linux. And when I open the app and press "Create project", I get the following error on the console:

> (WebKitWebProcess:317203): Gdk-ERROR **: 11:38:28.478: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 217 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Environment (if possible, copy the information from the error dialog or the About menu):**
- Linux lenovo 5.11.0-7614-generic #15~1622578982~20.10~383c0a9-Ubuntu SMP Wed Jun 2 00:54:41 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
 - Kreya Version 1.5.0

**Comment by CommonGuy** [comment] 2021-07-20 15:06
Did you install Kreya via snap or via tarball?

**Comment by Serkan80** [comment] 2021-07-20 15:52
I tried both, and with both I got the same error

**Comment by CommonGuy** [comment] 2021-08-02 13:34
Cannot reproduce this, works fine for me (Ubuntu 20.04)... This bug usually indicates issues with graphic drivers. Do you have a NVIDIA proprietary driver?

Do you have additional stdout/stderr output when launching from the command line? Could you provide the content of the logfile (should be at `~/.config/Kreya/kreya.log`)?

**Comment by Serkan80** [comment] 2021-08-03 10:25
@CommonGuy yes, I use a proprietary NVIDIA driver that comes with PopOS installation.

And here is the output of the log:

> System.Exception: Script execution failed with: ""
   at SpiderEye.Linux.GtkWebview.ExecuteScriptCallback(IntPtr webview, IntPtr asyncResult, IntPtr userdata)
   at SpiderEye.Linux.GtkWebview.<>c__DisplayClass44_0.<ExecuteScriptAsync>b__0(IntPtr webview, IntPtr asyncResult, IntPtr userdata)
--- End of stack trace from previous location ---
   at SpiderEye.Linux.GtkWebview.ExecuteScriptAsync(String script)
   at SpiderEye.Bridge.WebviewBridge.EndApiCall(InvokeInfoModel info, ApiResultModel result)
   at SpiderEye.Bridge.WebviewBridge.<>c__DisplayClass32_0.<<HandleScriptCall>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at SpiderEye.Bridge.WebviewBridge.HandleScriptCall(String data)
   at SpiderEye.Linux.GtkWebview.ScriptCallback(IntPtr manager, IntPtr jsResult, IntPtr userdata)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at SpiderEye.Linux.GtkSynchronizationContext.InvokeCallback(IntPtr data)
2021-07-20 11:40:06.808 +02:00 [WRN] The 'bool' property 'Unique' on entity type 'AppInfo' is configured with a database-generated default. This default will always be u>

**Comment by CommonGuy** [comment] 2021-08-03 11:38
Not sure if we can do much on our end, since this seems like a bug with WebKit (which Kreya uses) and the proprietary NVIDIA driver.

Could you try setting the `WEBKIT_DISABLE_COMPOSITING_MODE=1` environment variable and see if this workaround fixes the problem?

**Comment by Serkan80** [comment] 2021-08-03 11:57
Thx for your feedback.

This works for me:
> WEBKIT_DISABLE_COMPOSITING_MODE=1 ./kreya

**Comment by CommonGuy** [comment] 2021-08-03 12:05
Glad we could find a workaround :) Closing this since we can't do much from our end

**Closed by CommonGuy** 2021-08-03 12:05 UTC
Labels: bug, status:needs-info
