### ISSUE TITLE
Dynamic authentication support

### ISSUE THREAD

**Issue by msasidharan** [riok/Kreya#188] opened 2023-12-23 00:36 UTC
**Describe the bug**
When authentication is defined as a static value - Bearer {{ vars.token }}, when a service is invoked and populates the variable token, the new value is not picked up until edit authentication and save action is performed (of course with no changes).

**To Reproduce**
1. Define/use an API say Login that populates token. 
2. Put the following in the script tab:
kreyaGrpc.onResponse(msg => {
  kreya.variables.set("token", msg.content.token);
});
3. Try to invoke another service/api that uses this auth
4. Define its authentication as auth1 with Bearer {{ vars.token }}
5. Hit Send - it works
6. Go and invoke Login (API in step 1)
7. Come back and invoke the api in step 3
8. See error
9. Just edit authentication auth1 (just save - no changes)
10. Invoke api -- it works

**Expected behavior**
Authentication should just get updated whenever the value of variable changes. Invoking api at step 7 should succeed.

**Screenshots**
N/A

**Environment (if possible, copy the information from the error dialog or the About menu):**
- OS Windows 10
 - Kreya Version 1.12.0

**Additional context**
None

**Comment by latonz** [comment] 2023-12-28 03:48
Thank you for reporting this. This seems to be a duplicate of https://github.com/riok/Kreya/issues/188. A BugFix is in the backlog for the next release.

**Closed by latonz** 2023-12-28 03:48 UTC
Labels: bug
